default: &default
  adapter: postgresql
  encoding: unicode
  username: boverius
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: boverius_development

test:
  <<: *default
  host: localhost
  database: boverius_test

production:
  <<: *default
  database: boverius_production
  password: <%= ENV['BOVERIUS_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
