# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6396fa032fdd86e72107a8d988aaa44ddd120d0de2862121928eb56d769686bba30cf24ba07ea1e629c55d5b0e68cbee545b64d9430d533f5ca936de81efa3

test:
  secret_key_base: 683043cda4dcc61e9cc4bc3a68331410d76c5c792398d652a4b0775d150441d0bf141601891f4a3b515006bc4cfc04b6aef247b4dc1fae119304d56e03665e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: 683043cda4dcc61e9cc4bc3a68331410d76c5c792398d652a4b0775d150441d0bf141601891f4a3b515006bc4cfc04b6aef247b4dc1fae119304d56e03665e6a
   secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
